### ISSUE TITLE
Reproducing Typilus results

### ISSUE THREAD

**Issue by fraolBatole** [typilus/typilus#14]
Hello,

Is there a way to get the trained model using the original dataset? I read that you can't share the data, but I wonder if anyone has a trained model we can use to predict types (if possible)?

**Comment by mallamanis** [comment]
Hi @fraolBatole unfortunately releasing models has the same constraints as releasing data. This means that at the time it was not possible to release the trained model. In any case, as I have now changed employer the trained models are now lost. Apologies.
